import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Landing from "./../components/landing/landing";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Clinics</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Landing />
      </main>
    </div>
  );
}
